global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'katpool-app'
    static_configs:
      - targets: ['katpool-app:9999']

  - job_name: 'katpool-monitor'
    static_configs:
      - targets: ['katpool-monitor:9300']

  # - job_name: 'katpool-pushgateway'
  #   static_configs:
  #     - targets: ['katpool-pushgateway:9091']
    